- src/state_writer.rs
- state_db.js
- test/database.spec.js
- test/statedb.spec.js
- types.d.ts
This PR resolves #20 and resolves #21
- Store snapshot in map instead of one value
- Reset DB before executing the test
- Added unit test
> Add multiple snapshot feature, and fix a non deterministic test - Closes #20 and #21

- .gitignore
- src/smt.rs
This PR resolves #34
Duplicated code in `smt.rs` was replaced with a function calls.
> Remove duplicated code - Closes #34

- src/codec.rs
- src/diff.rs
- src/in_memory_smt.rs
- src/smt.rs
- src/smt_db.rs
- src/state_db.rs
- src/state_writer.rs
- src/utils.rs
This PR resolves #36
Convert `Vec<u8>` -> `&[u8]` as arguments, if it is better option.
> Replace Vec<u8> -> &[u8] - Closes #36

- src/smt.rs
This PR resolves #33
All recursive functions (`tree_hasher`, `calculate_subtree` and `calculate_query_hashes`) except `SparseMerkleTree::update_node` function were translated into iterative functions.
`SparseMerkleTree::update_node` was not changed and if later needed to be iterative one, another issue will be created.
> Recursive functions are translated into iterative functions - Closes #33

- src/batch.rs
- src/codec.rs
- src/db.rs
- src/diff.rs
- src/in_memory_db.rs
- src/in_memory_smt.rs
- src/smt.rs
- src/state_db.rs
- src/state_writer.rs
- src/types.rs
- src/utils.rs
This PR resolves #37
Code was refactored to use `reference`, `Arc`, `Mutex` and their combinations to replace `.clone()` function calls.
Some `.clone()` function calls are still in the code because they really need to be there or it won't benefit if they were removed or the code will become messed up if `.clone()` functions would be removed and replaced with any of the techniques used to remove such function calls.
> Reduce the number of .clone() function calls - Closes #37

- database.js
- src/common_db.rs
- src/db.rs
- src/lib.rs
- src/state_db.rs
- state_db.js
- test/database.spec.js
- test/statedb.spec.js
- types.d.ts
This PR resolves #54 
Function for creating RocksDB checkpoint for `Database` and `StateDB` is exposed to JS library and it is possible to call it from JS code.
- some new tests were implemented
- all tests passed
> Add RocksDB create checkpoint interface - Closes #54

- src/db.rs
- src/in_memory_db.rs
- src/lib.rs
- src/state_db.rs
- src/state_writer.rs
- state_db.js
- test/statedb.spec.js
This PR resolves #35 
- Reduce the number of rust call to one for each function in `JS` side
- Compare the speed of the execution between old implementation and new one, post the result on `slack` channel.
> Reduce the number of Rust call in JS side - Closes #35

- src/common_db.rs
- src/in_memory_db.rs
- src/lib.rs
- src/options.rs
- src/state_db.rs
- src/types.rs
This PR resolves #66 
- Introduce a new base struct for `types::Options`
- Introduce two new structs from `types::Options` for `DbOptions` and `CommitOptions`
> Fix a variable name and its usage - Closes #66

- src/common_db.rs
- src/lib.rs
- src/smt.rs
- src/state_db.rs
- test/database.spec.js
- test/statedb.spec.js
This PR resolves #65
- Fixed a bug in `smt.rs` module (`calc_query_proof_from_result` function)
- Fixed a bug in `state_db.rs` module (`prove` and `js_verify` functions)
- Fixed a bug where some JS unit tests randomly fail
- Some new JS unit tests were implemented
> Fix prove/verify interface between JS and Rust - Closes #65

- src/smt.rs
- state_db.js
- test/statedb.spec.js
This PR resolves #70
- Fixed addition overflow issue in `find_current_node` function in `smt.rs`
- Forced to use different memory space from what's given from binding for `prove` function in `state_db.js`
- Two new JS unit tests were implemented
- All tests passed
> Fix memory binding issue in db.prove function - Closes #70

- src/database/db.rs
- src/database/db_base.rs
- src/database/reader_writer/reader_base.rs
- src/database/traits.rs
- src/database/types.rs
- src/lib.rs
- src/state/state_db.rs
- test/database.spec.js
This PR resolves #78
- Refactor the `DB` to stores an `option` of DB and change it to `None` in `close` function.
- Add a new unit test to check the new implementation.
> Fix closing DB which leaves the database locked

- src/database/reader_writer/read_writer_db.rs
- src/types.rs
- test/statedb.spec.js
This PR resolves #83 
Update range iteration to cache key-value pair without prefix and return value without key
- Fix test to check the key as well
> Fix stateDB range

- Cargo.lock
- Cargo.toml
- benchmark/state_long.js
- src/database/reader_writer/read_writer_db.rs
- src/database/reader_writer/reader_base.rs
- src/lib.rs
- src/sparse_merkle_tree/smt.rs
- src/state/state_writer.rs
- state_db.js
- test/statedb.spec.js
- types.d.ts
- This PR resolves memory increment which is described in issue #88
- There is some memory leaks on `instruments` so the issue should be still open.
- Implement `close` functions for `ReadWriter` to close the connection.
- Define an empty function for  `StateWriter` to call it from JS.
- Finally implement `close` function for `StateReadWriter` in `state_db.js` to release the memory.
- Add a new unit test to check close function in JS.
- Also add a new unit test to check multi_thread usage for StateWriter.
- The result of the `Instruments` for `state_long.js` shows memory usage will be drop when GC is running by JS.
- It depends on the running machine (also the number of iterations for `inner` and `outer` loops) but it should be remain fixed during the execution when …
> Edit to fix increacing memory usage

- install.js
This PR resolves #96 
- Remove the build flag to fetch the pre built binary
> Fix install not to build from scratch

- package.json
This PR resolves #97 
- Move the build tools to be in dependencies in case it needs to build on install
> Update build tools to be in dependencies

- .github/PULL_REQUEST_TEMPLATE.md
- src/sparse_merkle_tree/in_memory_smt.rs
- src/sparse_merkle_tree/smt.rs
- src/state/state_db.rs
- test/sparse_merkle_tree.spec.js
This PR resolves #99 
- Add check on `verify_query_keys`
- Added unit test to verify zero byte append and prepend bitmap proof
> Fix proof verification for zero append bitmap

- benchmark/iterator.js
- database.js
- iterator.js
- test/database.spec.js
This PR resolves #103 
- Remove logic from `_read` and move to constructor because `_read` will be called for number of times data is emitted.
- Run the iterator benchmark (node benchmark/iterator.js)
- All tests should pass
> Fix iterator function not to be called multiple times

- src/sparse_merkle_tree/smt.rs
- This PR resolves #107.
- `SparseMerkleTree::verify` function checks lengths of leaf keys in the provided proof.
- New unit tests were added.
- All previous unit tests passed.
> Fix checking lengths of leaf keys in the provided proof in smt::verify function

- src/state/state_writer.rs
- src/utils.rs
- This PR resolves #105.
- Decrease loop iterations for `test_multi_thread` unit test.
- Missing return statement in `common_prefix` function was added.
- On some machines while executing `test_multi_thread` unit test it could occur buffer overflow or out of memory error. Because of that loop iterations were decreased.
- New unit tests were added.
- All previous unit tests passed.
> Fix `common_prefix` method

- .github/workflows/pr.yaml
- .github/workflows/publish-canary.yaml
- .github/workflows/publish.yaml
- package.json
- test/database.spec.js
- test/statedb.spec.js
- yarn.lock
This PR resolves #90.
- `package.json` was updated to support both Node.js 16 and 18.
- GitHub workflows were updated to use Node.js 16 and 18 for builds.
- Removed unnecessary directory cleanup after some JS unit test executions.
> Support Node.js 16 and 18

- .github/workflows/publish-canary.yaml
A bug for canary build was introduced within PR #113 for issue #90.
When publishing `npm` only `Node.js` 18 is used.
Canary workflow successfully passed.
> Fixed canary build for Node.js 16 and 18

- src/diff.rs
- src/sparse_merkle_tree/smt.rs
- src/state/state_db.rs
- src/state/state_writer.rs
- test/database.spec.js
- test/sparse_merkle_tree.spec.js
- test/statedb.spec.js
This PR resolves #125 
Update to separate empty value and deleted value
Updated unit tests in rust and added functional tests in JS
> Fix statedb to differentiate empty value and delete

- src/sparse_merkle_tree/smt.rs
- src/utils.rs
This PR resolves #129.
Before inserting data into SMT, key length is checked and error is thrown in case of invalid length.
- New unit tests were added.
- All previous unit tests passed.
> Key length is checked when updating the SMT

- Cargo.lock
- Cargo.toml
- sparse_merkle_tree.js
- src/sparse_merkle_tree/smt.rs
- test/sparse_merkle_tree.spec.js
This PR resolves #132.
- Implemented missing check that the `queries` length is equal to length of `proof.queries` before the loop in `verifyInclusionProof` and `verifyNonInclusionProof` functions.
- Bumping `RocksDB` version from `0.19` to `0.21` to make CI on Windows machine working.
- Fixed handling of invalid non-inclusion proof.
- New unit tests were added.
- All previous unit tests passed.
> Added missing checks and handling of invalid non-inclusion proof in `smt.rs`
